export const SURVEY_DETAILS_MAPPER = 'SURVEY_DETAILS_MAPPER';
export const STORAGE_SERVICE = 'storage';
export const AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE';
export const TOKEN_HANDLER = "TOKEN_HANDLER";
export const SUMMARIES_SERVICE = "SUMMARIES_SERVICE";
export const START_SURVEY_SERVICE = "START_SURVEY_SERVICE";